# Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: "WSO2 Integrator: SI Documentation"
site_description: "Documentation for WSO2 Integrator: SI"
site_author: WSO2
site_url: https://si.docs.wso2.com/

# Repository information
repo_name: wso2/docs-streaming-integrator
repo_url: https://github.com/wso2/docs-si
edit_uri: https://github.com/wso2/docs-si/edit/main/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: "WSO2 Integrator: SI - Documentation"

# Configuration
theme:
  name: material
  palette:
    primary: default
  custom_dir: theme/material
  logo: images/logo.svg
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Strict Mode
strict: false # Set to true to break the build if there are warnings

# Markdown extensions configuration
# Extensions
markdown_extensions:
    - fenced_code
    - codehilite

extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  # site_version: Uncomment to specify a version
  # base_path: http://localhost:8000/
  base_path: https://wso2.github.io/docs-si